# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Film_genre_choose_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Film_page(object):
    def setupUi(self, Film_page):
        Film_page.setObjectName("Film_page")
        Film_page.resize(640, 480)
        font = QtGui.QFont()
        font.setPointSize(9)
        Film_page.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Film_page)
        self.centralwidget.setObjectName("centralwidget")
        self.genre_box = QtWidgets.QComboBox(self.centralwidget)
        self.genre_box.setGeometry(QtCore.QRect(230, 50, 121, 31))
        self.genre_box.setObjectName("genre_box")
        self.genre_box.addItem("")
        self.genre_box.addItem("")
        self.genre_box.addItem("")
        self.genre_box.addItem("")
        self.genre_box.addItem("")
        self.genre_box.addItem("")
        self.genre_lab = QtWidgets.QLabel(self.centralwidget)
        self.genre_lab.setGeometry(QtCore.QRect(260, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.genre_lab.setFont(font)
        self.genre_lab.setObjectName("genre_lab")
        self.book_nice_lab = QtWidgets.QLabel(self.centralwidget)
        self.book_nice_lab.setGeometry(QtCore.QRect(70, 300, 521, 81))
        self.book_nice_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.book_nice_lab.setFont(font)
        self.book_nice_lab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.book_nice_lab.setObjectName("book_nice_lab")
        self.continue_next_page = QtWidgets.QPushButton(self.centralwidget)
        self.continue_next_page.setGeometry(QtCore.QRect(450, 50, 93, 28))
        self.continue_next_page.setObjectName("continue_next_page")
        Film_page.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Film_page)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        self.menuFilm_page = QtWidgets.QMenu(self.menubar)
        self.menuFilm_page.setObjectName("menuFilm_page")
        Film_page.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Film_page)
        self.statusbar.setObjectName("statusbar")
        Film_page.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFilm_page.menuAction())

        self.retranslateUi(Film_page)
        QtCore.QMetaObject.connectSlotsByName(Film_page)

    def retranslateUi(self, Film_page):
        _translate = QtCore.QCoreApplication.translate
        Film_page.setWindowTitle(_translate("Film_page", "MainWindow"))
        self.genre_box.setItemText(0, _translate("Film_page", "ფანტასტიკა"))
        self.genre_box.setItemText(1, _translate("Film_page", "ფენტეზი"))
        self.genre_box.setItemText(2, _translate("Film_page", "საშინელება"))
        self.genre_box.setItemText(3, _translate("Film_page", "კომედია"))
        self.genre_box.setItemText(4, _translate("Film_page", "დოკუმენტური"))
        self.genre_box.setItemText(5, _translate("Film_page", "დეტექტივი"))
        self.genre_lab.setText(_translate("Film_page", "ჟანრა"))
        self.book_nice_lab.setText(_translate("Film_page", "choose your favourite genre and enjoy!! ;)"))
        self.continue_next_page.setText(_translate("Film_page", "გაგრძელება"))
        self.menuFilm_page.setTitle(_translate("Film_page", "Film.page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Film_page = QtWidgets.QMainWindow()
    ui = Ui_Film_page()
    ui.setupUi(Film_page)
    Film_page.show()
    sys.exit(app.exec_())
