# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_My_cinema_ge(object):
    def setupUi(self, My_cinema_ge):
        My_cinema_ge.setObjectName("My_cinema_ge")
        My_cinema_ge.resize(640, 480)
        My_cinema_ge.setSizeIncrement(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setPointSize(9)
        My_cinema_ge.setFont(font)
        My_cinema_ge.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(My_cinema_ge)
        self.centralwidget.setObjectName("centralwidget")
        self.agrrement_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.agrrement_check_box.setGeometry(QtCore.QRect(10, 400, 171, 20))
        self.agrrement_check_box.setObjectName("agrrement_check_box")
        self.anime_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.anime_btn_2.setGeometry(QtCore.QRect(330, 180, 93, 28))
        self.anime_btn_2.setObjectName("anime_btn_2")
        self.zazaBtn = QtWidgets.QPushButton(self.centralwidget)
        self.zazaBtn.setGeometry(QtCore.QRect(440, 180, 93, 28))
        self.zazaBtn.setObjectName("zazaBtn")
        self.manga_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manga_btn.setGeometry(QtCore.QRect(540, 180, 93, 28))
        self.manga_btn.setObjectName("manga_btn")
        self.film_btn = QtWidgets.QPushButton(self.centralwidget)
        self.film_btn.setGeometry(QtCore.QRect(10, 180, 93, 28))
        self.film_btn.setObjectName("film_btn")
        self.TVseriers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.TVseriers_btn.setGeometry(QtCore.QRect(110, 180, 93, 28))
        self.TVseriers_btn.setObjectName("TVseriers_btn")
        self.animation_btn = QtWidgets.QPushButton(self.centralwidget)
        self.animation_btn.setGeometry(QtCore.QRect(220, 180, 93, 28))
        self.animation_btn.setObjectName("animation_btn")
        self.rules_lab = QtWidgets.QLabel(self.centralwidget)
        self.rules_lab.setGeometry(QtCore.QRect(0, 310, 241, 91))
        self.rules_lab.setObjectName("rules_lab")
        self.Sabas_cinema_lab = QtWidgets.QLabel(self.centralwidget)
        self.Sabas_cinema_lab.setGeometry(QtCore.QRect(180, 50, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        self.Sabas_cinema_lab.setFont(font)
        self.Sabas_cinema_lab.setTabletTracking(False)
        self.Sabas_cinema_lab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Sabas_cinema_lab.setToolTipDuration(93)
        self.Sabas_cinema_lab.setObjectName("Sabas_cinema_lab")
        self.comment_lab = QtWidgets.QLabel(self.centralwidget)
        self.comment_lab.setGeometry(QtCore.QRect(350, 330, 271, 61))
        self.comment_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comment_lab.setSizeIncrement(QtCore.QSize(10, 10))
        self.comment_lab.setBaseSize(QtCore.QSize(0, -7936))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comment_lab.setFont(font)
        self.comment_lab.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.comment_lab.setToolTipDuration(-1)
        self.comment_lab.setFrameShadow(QtWidgets.QFrame.Raised)
        self.comment_lab.setLineWidth(10000)
        self.comment_lab.setMidLineWidth(10005)
        self.comment_lab.setObjectName("comment_lab")
        My_cinema_ge.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(My_cinema_ge)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        self.menuMy_cinema_ge = QtWidgets.QMenu(self.menubar)
        self.menuMy_cinema_ge.setObjectName("menuMy_cinema_ge")
        My_cinema_ge.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(My_cinema_ge)
        self.statusbar.setObjectName("statusbar")
        My_cinema_ge.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMy_cinema_ge.menuAction())

        self.retranslateUi(My_cinema_ge)
        QtCore.QMetaObject.connectSlotsByName(My_cinema_ge)

    def retranslateUi(self, My_cinema_ge):
        _translate = QtCore.QCoreApplication.translate
        My_cinema_ge.setWindowTitle(_translate("My_cinema_ge", "MainWindow"))
        self.agrrement_check_box.setText(_translate("My_cinema_ge", "ვეთანხმები პირობებს"))
        self.anime_btn_2.setText(_translate("My_cinema_ge", "ანიმე"))
        self.zazaBtn.setText(_translate("My_cinema_ge", "წიგნი"))
        self.manga_btn.setText(_translate("My_cinema_ge", "მანგა"))
        self.film_btn.setText(_translate("My_cinema_ge", "ფილმი"))
        self.TVseriers_btn.setText(_translate("My_cinema_ge", "სერიალი"))
        self.animation_btn.setText(_translate("My_cinema_ge", "ანიმაცია"))
        self.rules_lab.setText(_translate("My_cinema_ge", "პირობები: რამეს თუ აირჩევ, ნახე!!!!"))
        self.Sabas_cinema_lab.setText(_translate("My_cinema_ge", "My.Cinema.ge"))
        self.comment_lab.setText(_translate("My_cinema_ge", "choose, check, judge and enjoy."))
        self.menuMy_cinema_ge.setTitle(_translate("My_cinema_ge", "My.cinema.ge"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    My_cinema_ge = QtWidgets.QMainWindow()
    ui = Ui_My_cinema_ge()
    ui.setupUi(My_cinema_ge)
    My_cinema_ge.show()
    sys.exit(app.exec_())




# layout.addWidget(label)
# layout.addWidget(checkbox)
